
#docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --mysql > initdb.sql
#docker exec -i guacamole_db mysql --user anyblabla --password=blabla guacamole_db < initdb.sql
#User: guacadmin 
#password: guacadmin
# mkdir guacamole
# touch docker-compose-yml
# nano docker-compose.yml
# Não se esqueça de personalizar a senha “root” do MySQL…
#-  MYSQL_ROOT_PASSWORD=blablalinux
# Não se esqueça de personalizar o nome de usuário do MySQL…
# MYSQL_USER=anyblabla
# Não se esqueça de personalizar a senha do MySQL…
# MYSQL_PASSWORD=blabla
#    A informação de “ambiente” do serviço “guacamole_db” deve ser idêntica à informação de “ambiente” do serviço “guacamole”!
#    A variável “- REMOTE_IP_VALVE_ENABLED=” deve ser ativada se você usar um Proxy Reverso
#    - REMOTE_IP_VALVE_ENABLED=true
#   docker-compose up -d
#   sudo su
#   docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --mysql > initdb.sql
#   docker exec -i guacamole_db mysql --user anyblabla --password=blabla guacamole_db < initdb.sql
#   A ordem deve ser adaptada ao seu ambiente…
#   -user anyblabla --password=blabla
#  https://wiki.blablalinux.be/fr/docker-compose-apache-guacamole


version: '3.8'

services:
    guacamole_db:
        container_name: guacamole_db
        hostname: guacamole_db
        image: mariadb:10.11
        restart: always
        volumes:
            - ./guacamole_db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=blablalinux
            - MYSQL_DATABASE=guacamole_db
            - MYSQL_USER=anyblabla
            - MYSQL_PASSWORD=blabla
        expose:
            - 3306

    guacd:
        container_name: guacd
        hostname: guacd
        image: guacamole/guacd:latest
        restart: always
        volumes:
            - ./guacd_drive:/drive:rw
            - ./guacd_record:/record:rw
        expose:
            - 4822

    guacamole:
        container_name: guacamole
        hostname: guacamole
        restart: always
        image: guacamole/guacamole:latest
        depends_on:
            - guacamole_db
            - guacd
        ports:
            - 8080:8080
        links:
            - guacd
        environment:
            - GUACD_HOSTNAME=guacd
            - MYSQL_HOSTNAME=guacamole_db
            - MYSQL_DATABASE=guacamole_db
            - MYSQL_USER=anyblabla
            - MYSQL_PASSWORD=blabla
            - REMOTE_IP_VALVE_ENABLED=true